name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  labeled:
    if: ${{ github.event.action == 'labeled' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: ${{ true }}
