name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  labeled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo github.event
      - run: ${{  github.event_name == 'pull_request' && github.event.action == 'labeled' }}
