name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    if: ${{ github.event.action == 'labeled' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: job.status="success"

  build2:
    if: ${{ github.event.action != 'labeled' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: job.status="failure"
